from src.backend.pieces.piece import Square
from src.backend.pieces.pawn import Pawn
from src.backend.pieces.queen import Queen


moves = [
    # Invalid moves
    ('Invalid move - white queen jump over pawn',
        ['D1 D3'],
        [Queen(is_white=True, location=(3,0))]),
    ('Invalid move - black queen jump over pawn',
        ['D2 D4','D7 D5','D1 D3', 'D8 D5', 'E7 E5'],
        [Pawn(is_white=False, location=(3,4)),
         Pawn(is_white=False, location=(4,4)),
         Queen(is_white=True, location=(3,2)),
         Queen(is_white=False, location=(3,7))]),
    # White queen movements
    ('White queen postive vertical movement',
        ['D2 D4','A7 A5','D1 D3'],
        [Queen(is_white=True, location=(3,2))]),
    ('White queen negative vertical movement',
        ['D2 D4','A7 A5','D1 D3','F7 F5','D3 D1'],
        [Queen(is_white=True, location=(3,0))]),
    ('White queen positive horizontal movement',
        ['D2 D4','A7 A5','D1 D3','B7 B5','D3 H3'],
        [Queen(is_white=True, location=(7,2))]),
    ('White queen negative horizontal movement',
        ['D2 D4','A7 A5','D1 D3','B7 B5','D3 A3'],
        [Queen(is_white=True, location=(0,2))]),
    ('White queen right diagonal movement',
        ['D2 D4','A7 A5','D1 D3','B7 B5','D3 F5'],
        [Queen(is_white=True, location=(5,4))]),
    ('White queen left diagonal movement',
        ['D2 D4','F7 F6','D1 D3','B7 B5','D3 A6'],
        [Queen(is_white=True, location=(3,2))]),
    ('White queen captures black pawn',
        ['D2 D4','A7 A5','D1 D3','B7 B5','D3 B3','F7 F5','B3 B5'],
        [Queen(is_white=True, location=(1,4))]),
    ('White queen moving over white pawn (invalid move)',
        ['D1 D4'],
        [Queen(is_white=True, location=(3,0))]),
    ('White queen captures white pawn (invalid move)',
        ['D1 D2'],
        [Queen(is_white=True, location=(3,0))]),
    # Black queen movements
    ('Black queen negative vertical movement',
        ['A2 A4','D7 D5','D2 D4','D8 D6'],
        [Queen(is_white=False, location=(3,5))]),
    ('Black queen positive vertical movement',
        ['D2 D4','D7 D5','A2 A4','D8 D6','G2 G4','D6 D8'],
        [Queen(is_white=False, location=(3,7))]),
    ('Black queen negative horizontal movement',
        ['D2 D4','D7 D5','A2 A4','D8 D6','G2 G4','D6 A6'],
        [Queen(is_white=False, location=(0,5))]),
    ('Black queen positive horizontal movement',
        ['D2 D4','D7 D5','A2 A4','D8 D6','G2 G4','D6 H6'],
        [Queen(is_white=False, location=(7,5))]),
    ('Black queen left diagonal movement',
        ['D2 D4','D7 D5','A2 A4','D8 D6','G2 G4','D6 A3'],
        [Queen(is_white=False, location=(0,2))]),
    ('Black queen right diagonal movement',
        ['D2 D4','D7 D5','A2 A4','D8 D6','G2 G4','D6 G3'],
        [Queen(is_white=False, location=(6,2))]),
    ('Black queen captures white pawn',
        ['A2 A3','D7 D5','G2 G4','D8 D6','G4 G5','D6 A3'],
        [Queen(is_white=True, location=(0,2))]),
    ('Black queen captures black pawn (invalid move)',
        ['A2 A3','D8 D7'],
        [Queen(is_white=False, location=(3,7))]),
    ('Black queen moving over black pawn (invalid move)',
        ['D2 D4','D8 D5'],
        [Queen(is_white=False, location=(3,7))]),
]

