from src.backend.pieces.piece import Square
from src.backend.pieces.rook import Rook


moves = [
    # White rook movements
    ('White rook positive vertical movement',
        ['A2 A4','A7 A5','A1 A3'],
        [Rook(is_white=True, location=(0,2))]),
    ('White rook negative vertical movement',
        ['A2 A4','A7 A5','A1 A3','B7 B5', 'A3 A1'],
        [Rook(is_white=True, location=(0,0))]),
    ('White rook positive horizontal movement',
        ['A2 A4','A7 A5','A1 A3', 'H7 H5', 'A3 G3'],
        [Rook(is_white=True, location=(6,2))]),
    ('White rook negative horizontal movement',
        ['A2 A4','A7 A5','A1 A3', 'H7 H5', 'A3 G3', 'H8 H6', 'G3 A3'],
        [Rook(is_white=True, location=(0,2))]),
    ('White rook captures black pawn',
        ['A2 A4','B7 B5','A1 A3', 'H7 H5', 'A3 B3', 'D7 D6', 'B3 B5'],
        [Rook(is_white=True, location=(1,4))]),
    ('White rook moving over white pawn (invalid move)',
        ['A1 A4'],
        [Rook(is_white=True, location=(0,0))]),
    ('White rook diagonal move (invalid move)',
        ['B2 B4','A7 A5','A1 C3'],
        [Rook(is_white=True, location=(0,0))]),
    ('White rook captures white pawn (invalid move)',
        ['A1 A2'],
        [Rook(is_white=True, location=(0,0))]),
    # Black rook movements
    ('Black rook negative vertical movement',
        ['A2 A4','A7 A5','A1 A3', 'A8 A6'],
        [Rook(is_white=False, location=(0,5))]),
    ('Black rook positive vertical movement',
        ['A2 A4','A7 A5','A1 A3', 'A8 A6', 'C2 C3', 'A6 A8'],
        [Rook(is_white=False, location=(0,7))]),
    ('Black rook negative horizontal movement',
        ['A2 A4','H7 H5','A1 A3', 'H8 H6','B2 B4','H6 A6'],
        [Rook(is_white=False, location=(0, 5))]),
    ('Black rook positive horizontal movement',
        ['A2 A4','A7 A5','A1 A3','A8 A6','B2 B4','A6 H6'],
        [Rook(is_white=False, location=(7, 5))]),
    ('Black rook captures pawn',
        ['A2 A4','A7 A5','A1 A3', 'A8 A6', 'A3 G3', 'A6 B6', 'C2 C3','B6 B2'],
        [Rook(is_white=True, location=(6,2)),
        Rook(is_white=False, location=(1,1))]),
    ('Black rook moving over black pawn (invalid move)',
        ['A2 A4', 'A8 A5'],
        [Rook(is_white=False, location=(0,7))]),
    ('Black rook diagonal move (invalid move)',
        ['A2 A4','A7 A5','B2 B3', 'A8 A6', 'B3 B4','A6 C4'],
        [Rook(is_white=False, location=(0,5))]),
    ('Black rook captures black pawn (invalid move)',
        ['A2 A4','H8 H7'],
        [Rook(is_white=False, location=(7,7))]),
]

